ENV:
  SEED: 2025
  NAME: DiffPoseTalk_Trainer
  DESCRIPTION: Train the diffusion model of DiffPoseTalk.
  OUTPUT_DIR: ./output
  VERBOSE: True

DATASET:
  NAME: HDTF_TFHP
  ROOT: ./data/
  HDTF_TFHP:
    COEF_STATS: "stats_train.npz"
    TRAIN: "train.txt"
    VAL: "val.txt"
    TEST: "test.txt"
    COEF_FPS: 25      # frames per second for coefficients (sequence fps)
    MOTIONS: 100      # number of motions per sample
    CROP: "random"    # crop strategy
    AUDIO_SR: 16000   # audio sampling rate
    N_PREV_MOTIONS: 10
    PAD_MODE: 'zero'
    USE_CONTEXT_AUDIO: True
    TRUNC_PROB1: 0.3
    TRUNC_PROB2: 0.4

DATALOADER:
  NUM_WORKERS: 4
  TRAIN:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 64

MODEL:
  NAME: DiffTalkingHead
  HEAD:
    ROT_REPR: 'aa'
    NO_HEAD_POSE: False
    AUDIO_MODEL: 'wav2vec2'
    AUDIO_DIM: 128
    STYLE_DIM: 128
    USE_INDICATOR: True
    ALIGN_MASK_WIDTH: 1
    USE_LEARNABLE_PE: False
  BACKBONE:
    NAME: DiffusionModel
    HIDDEN_SIZE: 512
    NUM_HIDDEN_LAYERS: 8
    NUM_ATTENTION_HEADS: 8
    DIFF_SCHEDULE: 'cosine'
    N_STEPS: 1000
  TAIL:
    MLP_RATIO: 4
    TYARGET: "sample" 
  GUIDING_CONDITIONS: 'audio,style'
  CFG_MODE: 'incremental' # 'full', 'incremental', 'none'

LOSS:
  NAME: "L2Loss"
  NO_CONSTRAIN_PREV: False
  GEOMETRIC:
    W_VERTEX: 2e6  # weight of the vertex loss
    W_VELOCITY: 1e7  # weight of the velocity loss
    W_SMOOTH: 1e5   # weight of the vertex acceleration regularization
  HEAD:
    W_ANGLE: 0.05  # weight of the head angle loss
    W_VELOCITY: 5.0 # weight of the head angular velocity loss
    W_SMOOTH: 0.5  # weight of the head angular acceleration regularization
    W_TRANS: 0.5

TRAINER:
  NAME: DiffPoseTalkTrainer

TRAIN:
  USE_ITERS: True
  MAX_ITERS: 200000
  PRINT_FREQ: 50
  SAVE_FREQ: 10000
  EVALUATE: True
  EVAL_FREQ: 5000

OPTIM:
  NAME: "adam"
  LR: 0.0001
  LR_SCHEDULER: "gradual"
  WARMUP_MULTIPLIER: 1
  LR_UPDATE_FREQ: 1

TEST:
  NO_TEST: False
  EVALUATOR: CodeTalkerEvaluator