ENV:
  SEED: 2025
  NAME: StyleEncoder_Trainer
  DESCRIPTION: Train the style encoder of DiffPoseTalk.
  OUTPUT_DIR: ./output
  VERBOSE: True
  USE_WANDB: True
  WANDB:
    KEY: a86716e4e39d88d76fec9260c7783f8eeef1edf8
    ENTITY: 3DVZHao
    PROJECT: 3DTalkingHead
    NAME: TrainingStyleEncoder
    NOTES: Training as the baseline model.
    TAGS: Baseline
    MODE: online

DATASET:
  NAME: HDTF_TFHP
  ROOT: ./data/
  HDTF_TFHP:
    COEF_STATS: stats_train.npz
    TRAIN: train.txt
    VAL: val.txt
    TEST: test.txt
    COEF_FPS: 25      # frames per second for coefficients (sequence fps)
    MOTIONS: 100      # number of motions per sample
    CROP: random    # crop strategy
    AUDIO_SR: 16000   # audio sampling rate

DATALOADER:
  NUM_WORKERS: 4
  TRAIN:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 64

MODEL:
  NAME: StyleEncoder
  HEAD:
    ROT_REPR: 'aa'
    NO_HEAD_POSE: False
  BACKBONE:
    NAME: TransformerEncoder
    IN_DIM: 50
    HIDDEN_SIZE: 128
    NUM_HIDDEN_LAYERS: 4
    NUM_ATTENTION_HEADS: 4
  TAIL:
    MLP_RATIO: 4

LOSS:
  NAME: NTXentLoss
  CONTRASTIVE:
    TEMPRATURE: 0.1

TRAINER:
  NAME: StyleEncoderTrainer

TRAIN:
  USE_ITERS: True
  MAX_ITERS: 200
  PRINT_FREQ: 5
  SAVE_FREQ: 20
  EVALUATE: True
  EVAL_FREQ: 20

OPTIM:
  NAME: adam
  LR: 0.0001
  LR_SCHEDULER: cosine
  LR_UPDATE_FREQ: 1

EVALUATE:
  EVALUATOR: TDTalkerEvaluator